name: kristof.threefold.io
on:
  push:
    branch: [development]

jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: pushing latest change on kristof.threefold.io
        uses: appleboy/ssh-action@master
        with:
          host: kristof.threefold.io
          username: webuser
          key: ${{ secrets.TF_SECRET }}
          port: 34022
          script: |
            cd /home/webuser/websites/www_kristof/
            git log -1
            git pull
